SCREEN_WIDTH = 700
SCREEN_HEIGHT = 450

SCREEN_CENTER = (SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2)

BUTTON_COLOR = (0, 0, 0)

PADDLE_WIDTH = 10
PADDLE_HEIGHT = 50

BALL_WIDTH = 10
BALL_HEIGHT = 10

AUDIO_ICON_WIDTH = 20
AUDIO_ICON_HEIGHT = 20
AUDIO_ICON_X = SCREEN_WIDTH - AUDIO_ICON_WIDTH
AUDIO_ICON_Y = SCREEN_HEIGHT - AUDIO_ICON_HEIGHT
